"""Documentation build orchestration over already-produced evidence artifacts."""

from __future__ import annotations

import shutil
import tempfile
from collections.abc import Generator
from contextlib import chdir, contextmanager, suppress
from pathlib import Path

from sphinx.cmd.build import build_main

from ternforge_docops._internal.allure import (
    curate_results,
    extract_result_links,
    generate_report,
)
from ternforge_docops._internal.living_specs import (
    publish_living_assets,
    render_living_specifications,
)
from ternforge_docops._internal.living_specs.models import LivingSpecificationsReport
from ternforge_docops._internal.resources import shared_docs_dir_path

_EVIDENCE_SOURCE = "ternforge-test-evidence.rst"
_EVIDENCE_DIR = "_traceability"
_EVIDENCE_XML = "ternforge-test-evidence.xml"
_LIVING_SOURCE = "ternforge-living-specifications.inc"
_LIVING_PAGE_DIR = Path("specifications/_generated")
_LIVING_ASSET_DIR = Path("_living-specs/assets")
_LIVING_SOURCE_HEADER = ".. Generated by Ternforge DocOps; do not edit.\n\n"
_LIVING_EMPTY_SOURCE = (
    "No BDD execution evidence was supplied to this build. Use the portal build "
    "with retained Allure results to render current executable behavior.\n"
)
_EVIDENCE_SOURCE_TEXT = (
    ":orphan:\n\n"
    "Test evidence\n"
    "=============\n\n"
    ".. test-file:: Imported test evidence\n"
    "   :id: TEST_EVIDENCE\n"
    f"   :file: {_EVIDENCE_DIR}/{_EVIDENCE_XML}\n"
    "   :auto_suites:\n"
    "   :auto_cases:\n"
)


def _run_sphinx(
    root: Path,
    docs_root: Path,
    output_root: Path,
    builder: str,
    *,
    live_examples: bool = False,
) -> None:
    """Run one strict Sphinx builder in the repository context."""
    arguments = ["-E", "-W", "--keep-going"]
    if not live_examples:
        arguments.extend(("-D", "plot_gallery=0"))
    if builder == "simplepdf":
        arguments.extend(("-D", "llms_txt_enabled=0"))
    arguments.extend(("-b", builder, str(docs_root), str(output_root)))
    with chdir(root):
        exit_code = build_main(arguments)
    if exit_code:
        message = f"Sphinx {builder} build failed with exit code {exit_code}"
        raise RuntimeError(message)


def _materialize_living_source(
    docs_root: Path,
    source: str | None,
    generated: list[Path],
) -> None:
    """Refresh the DocOps-reserved Living Specifications source for one build."""
    target = docs_root / _LIVING_SOURCE
    if target.exists():
        existing = target.read_text(encoding="utf-8")
        if not existing.startswith(_LIVING_SOURCE_HEADER):
            message = f"DocOps reserved Living Specifications source exists: {target}"
            raise RuntimeError(message)
        target.unlink()
    target.write_text(
        _LIVING_SOURCE_HEADER + (source or _LIVING_EMPTY_SOURCE),
        encoding="utf-8",
    )
    generated.append(target)


def _reset_living_page_tree(root: Path) -> None:
    """Remove an interrupted generated page tree only when DocOps owns every file."""
    if not root.exists():
        return
    files = [path for path in root.rglob("*") if path.is_file()]
    owns_tree = all(
        path.suffix == ".rst"
        and path.read_text(encoding="utf-8").startswith(_LIVING_SOURCE_HEADER)
        for path in files
    )
    if not owns_tree:
        message = f"DocOps reserved Living Specifications page tree exists: {root}"
        raise RuntimeError(message)
    shutil.rmtree(root)


def _living_page_target(docs_root: Path, docname: str) -> Path:
    """Resolve one generated page while enforcing the DocOps-reserved source tree."""
    relative = Path(f"{docname}.rst")
    try:
        relative.relative_to(_LIVING_PAGE_DIR)
    except ValueError as error:
        message = f"Living Specifications page is outside reserved tree: {docname}"
        raise RuntimeError(message) from error
    return docs_root / relative


def _materialize_living_pages(
    docs_root: Path,
    report: LivingSpecificationsReport | None,
    generated_dirs: list[Path],
) -> None:
    """Materialize one transient Sphinx source document per Gherkin Feature."""
    root = docs_root / _LIVING_PAGE_DIR
    _reset_living_page_tree(root)
    pages = () if report is None else getattr(report, "pages", ())
    if not pages:
        return
    for page in pages:
        target = _living_page_target(docs_root, page.docname)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_LIVING_SOURCE_HEADER + page.source, encoding="utf-8")
    generated_dirs.append(root)


def _materialize_living_assets(
    docs_root: Path,
    report: LivingSpecificationsReport | None,
    generated_dirs: list[Path],
) -> None:
    """Expose retained binary evidence to Sphinx while native directives resolve it."""
    root = docs_root / _LIVING_ASSET_DIR.parent
    shutil.rmtree(root, ignore_errors=True)
    if report is None or not report.assets:
        return
    target = docs_root / _LIVING_ASSET_DIR
    target.mkdir(parents=True, exist_ok=True)
    generated_dirs.append(root)
    for asset in report.assets:
        if asset.source is not None and asset.output_name is not None:
            shutil.copy2(asset.source, target / asset.output_name)


@contextmanager
def _materialized_sources(
    docs_root: Path,
    junit: Path | None,
    living_specs_source: str | None = None,
    living_report: LivingSpecificationsReport | None = None,
) -> Generator[None]:
    """Materialize package-owned views and optional evidence only for one build."""
    generated: list[Path] = []
    generated_dirs: list[Path] = []
    docs_root.mkdir(parents=True, exist_ok=True)

    for source in shared_docs_dir_path().glob("*.rst"):
        target = docs_root / source.name
        if target.exists():
            if target.read_bytes() == source.read_bytes():
                # Recover an exact package-owned copy left by an interrupted build.
                generated.append(target)
            continue
        target.write_bytes(source.read_bytes())
        generated.append(target)

    _materialize_living_source(docs_root, living_specs_source, generated)
    _materialize_living_pages(docs_root, living_report, generated_dirs)
    _materialize_living_assets(docs_root, living_report, generated_dirs)

    evidence_source = docs_root / _EVIDENCE_SOURCE
    trace_dir = docs_root / _EVIDENCE_DIR
    evidence_target = trace_dir / _EVIDENCE_XML

    # Interrupted local builds can be terminated before this context manager gets
    # a chance to clean its transient evidence files. Reconcile only DocOps-reserved
    # paths here so later builds neither import stale JUnit nor become wedged.
    if evidence_source.exists():
        if evidence_source.read_text(encoding="utf-8") != _EVIDENCE_SOURCE_TEXT:
            message = (
                f"DocOps reserved evidence source already exists: {evidence_source}"
            )
            raise RuntimeError(message)
        evidence_source.unlink()
    evidence_target.unlink(missing_ok=True)
    with suppress(OSError):
        trace_dir.rmdir()

    if junit is not None:
        junit = junit.resolve()
        if not junit.is_file():
            message = f"JUnit evidence does not exist: {junit}"
            raise FileNotFoundError(message)
        trace_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(junit, evidence_target)
        evidence_source.write_text(_EVIDENCE_SOURCE_TEXT, encoding="utf-8")
        generated.extend((evidence_source, evidence_target))

    try:
        yield
    finally:
        for path in reversed(generated):
            path.unlink(missing_ok=True)
        for path in reversed(generated_dirs):
            shutil.rmtree(path, ignore_errors=True)
        with suppress(OSError):
            (docs_root / _LIVING_PAGE_DIR.parent).rmdir()
        with suppress(OSError):
            trace_dir.rmdir()


def _prepare_living_specifications(
    root: Path,
    allure_results: Path,
    temp: Path,
) -> tuple[Path, LivingSpecificationsReport]:
    """Prepare Living Specs and the forensic Allure view from exact evidence."""
    curated = temp / "curated"
    curate_results(allure_results, curated_results=curated)
    report = generate_report(
        curated_results=curated,
        output=temp / "report",
    )
    living_report = render_living_specifications(
        root,
        allure_results,
        result_links=extract_result_links(report),
    )
    return report, living_report


def build_html(
    root: Path,
    *,
    docs: Path | None = None,
    output: Path | None = None,
    junit: Path | None = None,
    live_examples: bool = False,
) -> Path:
    """Build strict HTML documentation without executing project tests."""
    docs_root = docs or root / "docs"
    output_root = output or docs_root / "_build" / "html"
    with _materialized_sources(docs_root, junit):
        _run_sphinx(
            root,
            docs_root,
            output_root,
            "html",
            live_examples=live_examples,
        )
    return output_root


def build_dossier(
    root: Path,
    *,
    docs: Path | None = None,
    output: Path | None = None,
    junit: Path | None = None,
    allure_results: Path | None = None,
) -> Path:
    """Build the release dossier through the upstream SimplePDF Sphinx builder."""
    docs_root = docs or root / "docs"
    output_root = output or docs_root / "_build" / "dossier"
    if allure_results is None:
        with _materialized_sources(docs_root, junit):
            _run_sphinx(root, docs_root, output_root, "simplepdf")
        return output_root / "release-dossier.pdf"

    with tempfile.TemporaryDirectory(prefix="ternforge-docops-allure-") as temp_dir:
        _report, living_report = _prepare_living_specifications(
            root,
            allure_results,
            Path(temp_dir),
        )
        with _materialized_sources(
            docs_root,
            junit,
            living_report.source,
            living_report,
        ):
            _run_sphinx(root, docs_root, output_root, "simplepdf")
    return output_root / "release-dossier.pdf"


def build_portal(
    root: Path,
    *,
    allure_results: Path,
    output: Path | None = None,
    junit: Path | None = None,
    live_examples: bool = False,
) -> Path:
    """Build native Living Specs and one forensic Allure view."""
    docs_root = root / "docs"
    output_root = output or docs_root / "_build" / "html"
    with tempfile.TemporaryDirectory(prefix="ternforge-docops-allure-") as temp_dir:
        report, living_report = _prepare_living_specifications(
            root,
            allure_results,
            Path(temp_dir),
        )
        with _materialized_sources(
            docs_root,
            junit,
            living_report.source,
            living_report,
        ):
            _run_sphinx(
                root,
                docs_root,
                output_root,
                "html",
                live_examples=live_examples,
            )
        publish_living_assets(living_report, output_root)
        needs_json = output_root / "needs.json"
        if not needs_json.is_file():
            message = f"Sphinx build did not produce {needs_json}"
            raise RuntimeError(message)
        target = output_root / "test-results"
        shutil.rmtree(target, ignore_errors=True)
        target.mkdir(parents=True)
        shutil.copy2(report, target / "index.html")
    return output_root
